db:
  host: root:passwd@tcp(localhost:3306)/car_user
  max_idle_conns: 2
  conn_max_lifetime: 3
  max_open_conns: 0
  debug: false

transport:
  use_logger: true
  use_recovery: true
  api_prefix: api
  api_version: v1

redis:
  mode: "standalone"
  nodes:
    - 10.38.202.155:7617
  password: ""

log:
  format: "string" # string or json
  path: "/home/work/log/car"
  output: "/home/work/log/car/auth.log" # log path, or console: stdout, stderr
  level: "debug"